azure_sql:
  server: 'servidor-tfg-26.database.windows.net'
  database: 'DW_TFG'
  username: 'adminsql26'
  password: 'Tfg-2026'
  driver: '{ODBC Driver 17 for SQL Server}'

local_sql:
  server: 'localhost' # O el nombre de tu instancia, ej: 'localhost\SQLEXPRESS'
  database: 'DW_TFG'
  driver: '{ODBC Driver 17 for SQL Server}'